// GENERATED by frontend/scripts/generate-service-worker.mjs — edit map/webapp/sw.body.js
// shell version: 2d769871d80e (208 assets)
// region version: 2140162cf92c (47 regions)
'use strict';

/**
 * Service Worker キャッシュ方針（純粋関数のみ）
 * =============================================
 * ここには Cache API も DOM も出てこない。判断だけを置き、node:test で検証する。
 * sw.js はこのファイルを取り込んだ上で副作用を担当する。
 *
 * 最重要の境界:
 *
 *   動的防災データ (/map/data/**) を Service Worker がキャッシュしてはいけない。
 *
 * 避難所の開設状態・河川水位・警報・カメラは runtimeCache が鮮度を管理しており、
 * 「取得できたか / 保存済みを出しているか」を runtime:dataStatus で報告している。
 * SW が古い本文を 200 で返すと、その取得は「成功」に見えてしまい、鮮度バナーが
 * 二度と出なくなる。古い避難所情報を最新だと誤認させるのが最悪の失敗なので、
 * 動的データは必ずネットワークへ素通しし、失敗はそのまま失敗として伝える。
 */

const SHELL_CACHE_PREFIX = 'svg3-shell-';
const REGION_CACHE_PREFIX = 'svg3-region-';
const META_CACHE_NAME = 'svg3-meta-v1';

// 端末容量を食い潰さないための上限。1地域あたりハザード数MB + 地区SVG十数MB。
const MAX_CACHED_REGIONS = 3;

const REGION_ID_PATTERN = /^[a-z0-9][a-z0-9-]{0,31}$/;

// 動的データの保管庫。SW のキャッシュではなく、鮮度を管理している runtimeCache が
// 読む場所へ置く。SW が肩代わりすると取得が成功に見えて鮮度バナーが出なくなる。
// (map/layers/portable/representative-pins/runtimeCache.js と同じ値)
const RUNTIME_DATA_CACHE_NAME = 'svgmap-runtime-data-v1';
const RUNTIME_STORED_AT_HEADER = 'x-svg3-stored-at';

// SW が絶対に肩代わりしてはいけない領域（鮮度管理は runtimeCache の責任）。
const DYNAMIC_PREFIXES = [
  '/map/data/',
  '/map/distribution/',
];

// 地域ごとに変わる静的資産。
const REGION_PREFIXES = [
  '/map/containers/',
  '/map/layers/hazard/',
  '/map/layers/offline-basemap/',
  '/data/',
];

// 地域に依らず起動に要る静的資産。
const SHELL_PREFIXES = [
  '/map/webapp/',
  '/map/vendor/',
  '/map/layers/portable/',
  '/map/layers/dropins/',
  '/map/layers/external/',
  '/map/icons/',
  '/map/svgMapAppLayers/',
  '/icons/',
];

const SHELL_EXACT = [
  '/map/layers/catalog.json',
  '/map/regions/index.json',
  '/manifest.webmanifest',
];

const startsWithAny = (pathname, prefixes) =>
  prefixes.some((prefix) => pathname.startsWith(prefix));

const shellCacheName = (version) => `${SHELL_CACHE_PREFIX}${version}`;
const regionCacheName = (regionId, version) => `${REGION_CACHE_PREFIX}${regionId}-${version}`;

const isValidRegionId = (value) =>
  typeof value === 'string' && REGION_ID_PATTERN.test(value);

/**
 * キャッシュ名を分解する。svg3 が作ったものでなければ null（他アプリのキャッシュを
 * 巻き込んで消さないため）。
 */
const parseCacheName = (name) => {
  if (typeof name !== 'string') return null;
  if (name === META_CACHE_NAME) return { kind: 'meta', name };
  if (name.startsWith(SHELL_CACHE_PREFIX)) {
    const version = name.slice(SHELL_CACHE_PREFIX.length);
    return version ? { kind: 'shell', version, name } : null;
  }
  if (name.startsWith(REGION_CACHE_PREFIX)) {
    const rest = name.slice(REGION_CACHE_PREFIX.length);
    const separator = rest.lastIndexOf('-');
    if (separator <= 0) return null;
    const regionId = rest.slice(0, separator);
    const version = rest.slice(separator + 1);
    if (!regionId || !version) return null;
    return { kind: 'region', regionId, version, name };
  }
  return null;
};

/**
 * 要求の扱いを決める。
 *   'shell'    … 版付きキャッシュから先に返す（オフライン起動の要）
 *   'region'   … 閲覧地域として保存済みなら返す
 *   'dynamic'  … 必ずネットワーク。SW は一切肩代わりしない
 *   'external' … 別オリジン。触らない
 *   'ignore'   … 対象外
 */
const classifyRequest = ({ pathname, sameOrigin = true, method = 'GET' } = {}) => {
  if (method !== 'GET') return 'ignore';
  if (!sameOrigin) return 'external';
  if (typeof pathname !== 'string' || !pathname.startsWith('/')) return 'ignore';
  // 動的データの判定を最優先にする。ここを取り違えると鮮度バナーが死ぬ。
  if (startsWithAny(pathname, DYNAMIC_PREFIXES)) return 'dynamic';
  if (SHELL_EXACT.includes(pathname)) return 'shell';
  // /map/regions/index.json は shell、/map/regions/<id>/... は地域。
  if (pathname.startsWith('/map/regions/')) {
    return pathname.slice('/map/regions/'.length).includes('/') ? 'region' : 'shell';
  }
  if (startsWithAny(pathname, REGION_PREFIXES)) return 'region';
  if (startsWithAny(pathname, SHELL_PREFIXES)) return 'shell';
  return 'ignore';
};

const isDynamicPath = (pathname) =>
  classifyRequest({ pathname }) === 'dynamic';

/**
 * activate 時に消すキャッシュ名。
 *  - 旧 shell は消す（新旧の資産が混ざるとアプリが壊れる）
 *  - 地域キャッシュは版が変わったものだけ消す。shell 更新で無条件全削除はしない
 *    （災害時に保存済み地域を失うのが一番まずい）
 */
const obsoleteCacheNames = (existingNames, { shellVersion, regionVersion } = {}) => {
  const doomed = [];
  for (const name of existingNames || []) {
    const parsed = parseCacheName(name);
    if (!parsed) continue;
    if (parsed.kind === 'shell' && parsed.version !== shellVersion) doomed.push(name);
    if (parsed.kind === 'region' && regionVersion && parsed.version !== regionVersion) doomed.push(name);
  }
  return doomed;
};

const cachedRegionIds = (existingNames, regionVersion) => {
  const ids = [];
  for (const name of existingNames || []) {
    const parsed = parseCacheName(name);
    if (parsed?.kind !== 'region') continue;
    if (regionVersion && parsed.version !== regionVersion) continue;
    if (!ids.includes(parsed.regionId)) ids.push(parsed.regionId);
  }
  return ids;
};

/**
 * 上限を超えた分を、最後に使った順で古いものから落とす。
 * usageOrder は新しい順。載っていない地域は最も古い扱い。
 * pinned（利用者が明示保存した地域）は決して落とさない。
 */
const regionsToEvict = (regionIds, usageOrder = [], max = MAX_CACHED_REGIONS, pinned = []) => {
  const pinnedSet = new Set(pinned || []);
  const rank = (id) => {
    const index = usageOrder.indexOf(id);
    return index < 0 ? Number.MAX_SAFE_INTEGER : index;
  };
  const unique = [...new Set(regionIds || [])];
  // pin は席を占有するが追い出されない。自動保存分だけを古い順に落とす。
  const automatic = unique.filter((id) => !pinnedSet.has(id)).sort((a, b) => rank(a) - rank(b));
  const pinnedCount = unique.filter((id) => pinnedSet.has(id)).length;
  const room = Math.max(0, max - pinnedCount);
  return automatic.slice(room);
};

/**
 * 新しい地域を保存できるか決める。
 * 席が pin で埋まっているときは黙って消さず、利用者へ選択を求める。
 */
const planRegionCache = ({
  regionIds = [],
  incoming,
  pinned = [],
  usageOrder = [],
  max = MAX_CACHED_REGIONS,
} = {}) => {
  if (!isValidRegionId(incoming)) return { accepted: false, reason: 'invalid-region', evict: [] };
  const pinnedSet = new Set(pinned);
  const all = [...new Set([...regionIds, incoming])];
  if (all.length <= max) return { accepted: true, evict: [], needsChoice: false };

  const evict = regionsToEvict(all, [incoming, ...usageOrder], max, [...pinnedSet, incoming]);
  const survivors = all.filter((id) => !evict.includes(id));
  if (survivors.length <= max) {
    return { accepted: true, evict, needsChoice: false };
  }
  // 自動保存分を全部落としても入らない = pin で埋まっている。
  return {
    accepted: false,
    needsChoice: true,
    reason: 'capacity',
    evict: [],
    // 利用者に選ばせるのは「既に保存済みの pin」だけ。これから追加する地域を
    // 選択肢に混ぜると「gifu を消して gifu を入れる」という無意味な案内になる。
    pinnedRegions: all.filter((id) => pinnedSet.has(id) && id !== incoming),
    max,
  };
};

/**
 * 保存状態を実キャッシュの実在から決める。
 * メタデータだけ残っていても「保存済み」とは言わない。
 * 途中で通信が切れた不完全なキャッシュも「保存済み」とは言わない。
 */
const resolveRegionStatus = ({ meta, cacheExists = false, storedCount = 0 } = {}) => {
  if (!meta || !isValidRegionId(meta.regionId)) return { state: 'absent' };
  const expected = Number(meta.assetCount) || 0;
  const base = {
    regionId: meta.regionId,
    pinned: meta.pinned === true,
    savedAt: typeof meta.savedAt === 'string' ? meta.savedAt : null,
    bytes: Number(meta.bytes) || 0,
    expected,
    stored: storedCount,
  };
  // 実体が無ければ未保存。外部要因で消えた場合もここに落ちる。
  if (!cacheExists || storedCount === 0) return { ...base, state: 'absent' };
  if (meta.complete !== true || expected === 0 || storedCount < expected) {
    return { ...base, state: 'incomplete' };
  }
  return { ...base, state: 'saved' };
};

const savedRegionIds = (statuses) =>
  (statuses || []).filter((status) => status.state === 'saved').map((status) => status.regionId);

const touchRegionUsage = (usageOrder, regionId) => {
  if (!isValidRegionId(regionId)) return [...(usageOrder || [])];
  return [regionId, ...(usageOrder || []).filter((id) => id !== regionId)];
};

/** 地域資産マニフェストの検証。壊れた一覧で無差別保存させない。 */
const validateRegionAssetManifest = (manifest, regionId) => {
  if (!manifest || typeof manifest !== 'object') return null;
  if (manifest.kind !== 'svg3-region-assets') return null;
  if (regionId && manifest.regionId !== regionId) return null;
  if (!isValidRegionId(manifest.regionId)) return null;
  if (!Array.isArray(manifest.assets)) return null;
  // dataShards は動的データ。assets とは保存先が違うので別枠で検証する。
  const dataShards = (Array.isArray(manifest.dataShards) ? manifest.dataShards : []).filter((url) =>
    typeof url === 'string'
    && url.startsWith('/map/data/qtct/')
    && !url.includes('..')
    && !url.startsWith('//'));
  const assets = manifest.assets.filter((asset) =>
    typeof asset === 'string'
    && asset.startsWith('/')
    && !asset.startsWith('//')
    && !asset.includes('..')
    && classifyRequest({ pathname: asset }) === 'region');
  if (assets.length === 0) return null;
  return {
    regionId: manifest.regionId,
    assets: [...new Set(assets)],
    dataShards: [...new Set(dataShards)],
  };
};

/**
 * ページ ⇔ Service Worker のメッセージ契約（純粋関数のみ）
 * ========================================================
 * mapMessages.js と同じ考え方: 文字列リテラルを直書きせず、ここに集約する。
 * 検証は Service Worker API に触れずに済むので node:test で確かめる。
 */

const SW_MESSAGES = Object.freeze({
  cacheRegion: 'sw:cacheRegion',
  removeRegion: 'sw:removeRegion',
  listCachedRegions: 'sw:listCachedRegions',
});

const SW_RESULTS = Object.freeze({
  cachedRegions: 'sw:cachedRegions',
  regionCached: 'sw:regionCached',
  regionRemoved: 'sw:regionRemoved',
  regionProgress: 'sw:regionProgress',
  // 上限が pin で埋まっていて自動削除できないとき。黙って消さず選択を求める。
  capacityChoice: 'sw:capacityChoice',
  error: 'sw:error',
});

const SW_MESSAGE_REGION_ID = /^[a-z0-9][a-z0-9-]{0,31}$/;

const REQUIRES_REGION = new Set([
  SW_MESSAGES.cacheRegion,
  SW_MESSAGES.removeRegion,
]);

/**
 * ページから届いたメッセージを検証して正規化する。
 * 素性の知れない値をそのままキャッシュ操作に流さないための関門。
 * 受け付けられないものは null（= 黙って捨てる）。
 */
const parseSwMessage = (data) => {
  if (!data || typeof data !== 'object') return null;
  const type = data.type;
  if (typeof type !== 'string') return null;
  if (!Object.values(SW_MESSAGES).includes(type)) return null;

  if (!REQUIRES_REGION.has(type)) return { type };

  const regionId = data.regionId;
  if (typeof regionId !== 'string' || !SW_MESSAGE_REGION_ID.test(regionId)) return null;
  // pinned = 利用者が明示的に保存した地域。LRU の自動削除対象から外す。
  // 閲覧による自動保存では立てない。
  return { type, regionId, pinned: data.pinned === true };
};

/**
 * Service Worker 本体
 * ===================
 * このファイルは単体では動かない。scripts/generate-service-worker.mjs が
 * swCachePolicy.js / swMessages.js と束ねて classic script の map/sw.js を作る
 * （module Service Worker は iOS Safari で使えないため）。
 *
 * 設計の核心は「肩代わりしない領域」を厳密に守ること:
 *
 *   動的防災データ (/map/data/**) には respondWith を一切呼ばない。
 *   SW が古い本文を 200 で返すと取得が成功に見え、runtimeCache が
 *   キャッシュ退避を行わず、鮮度バナーが出なくなる。避難所の開設状態が
 *   古いまま「最新」として表示される事故に直結する。
 */



// --- 生成時に差し込まれる値 ------------------------------------------------
const SHELL_VERSION = "2d769871d80e";
const REGION_VERSION = "2140162cf92c";
const SHELL_ASSETS = [
  "/manifest.webmanifest",
  "/map/icons/app/icon-192.png",
  "/map/icons/app/icon-512.png",
  "/map/icons/current-location-pin.png",
  "/map/icons/current-location-pin.svg",
  "/map/icons/river-level-advisory.svg",
  "/map/icons/river-level-danger.svg",
  "/map/icons/river-level-evacuation.svg",
  "/map/icons/river-level-normal.svg",
  "/map/icons/river-level-stale.svg",
  "/map/icons/river-level-unknown.svg",
  "/map/icons/river-webcam.svg",
  "/map/icons/road-closure-cleared.svg",
  "/map/icons/road-closure-closed.svg",
  "/map/icons/road-closure-flooded.svg",
  "/map/icons/road-closure-restricted.svg",
  "/map/icons/road-closure-unknown.svg",
  "/map/icons/shelter-closed.png",
  "/map/icons/shelter-closed.svg",
  "/map/icons/shelter-default.png",
  "/map/icons/shelter-default.svg",
  "/map/icons/shelter-full.png",
  "/map/icons/shelter-full.svg",
  "/map/icons/shelter-limited.png",
  "/map/icons/shelter-limited.svg",
  "/map/icons/shelter-open.png",
  "/map/icons/shelter-open.svg",
  "/map/icons/team-active.png",
  "/map/icons/team-active.svg",
  "/map/icons/team-attention.png",
  "/map/icons/team-attention.svg",
  "/map/icons/team-completed.png",
  "/map/icons/team-completed.svg",
  "/map/icons/team-planned.png",
  "/map/icons/team-planned.svg",
  "/map/icons/team-standby.png",
  "/map/icons/team-standby.svg",
  "/map/layers/catalog.json",
  "/map/layers/portable/artifact-sample/artifactSampleLayer.html",
  "/map/layers/portable/artifact-sample/artifactSampleLayer.svg",
  "/map/layers/portable/artifact-sample/data/detail.json",
  "/map/layers/portable/artifact-sample/data/summary.json",
  "/map/layers/portable/artifact-sample/layer.package.json",
  "/map/layers/portable/current-location/currentLocationLayer.html",
  "/map/layers/portable/current-location/currentLocationLayer.svg",
  "/map/layers/portable/current-location/layer.package.json",
  "/map/layers/portable/evacuation/evacuationDetail.js",
  "/map/layers/portable/evacuation/evacuationLayer.html",
  "/map/layers/portable/evacuation/evacuationLayer.svg",
  "/map/layers/portable/evacuation/layer.package.json",
  "/map/layers/portable/flood-warning/floodWarningDetail.js",
  "/map/layers/portable/flood-warning/floodWarningLayer.html",
  "/map/layers/portable/flood-warning/floodWarningLayer.js",
  "/map/layers/portable/flood-warning/floodWarningLayer.svg",
  "/map/layers/portable/flood-warning/jmaWarnings.js",
  "/map/layers/portable/flood-warning/layer.package.json",
  "/map/layers/portable/hazard/hazardFallback.js",
  "/map/layers/portable/hazard/hazardLayer.html",
  "/map/layers/portable/hazard/hazardLayer.svg",
  "/map/layers/portable/hazard/layer.package.json",
  "/map/layers/portable/japan-river-webcams/layer.package.json",
  "/map/layers/portable/japan-river-webcams/webcamDetail.js",
  "/map/layers/portable/japan-river-webcams/webcamLayer.html",
  "/map/layers/portable/japan-river-webcams/webcamLayer.svg",
  "/map/layers/portable/representative-pins/densityPointFormat.js",
  "/map/layers/portable/representative-pins/mapMessages.js",
  "/map/layers/portable/representative-pins/observationFreshness.js",
  "/map/layers/portable/representative-pins/pinLayerProfiles.js",
  "/map/layers/portable/representative-pins/propertyModal.js",
  "/map/layers/portable/representative-pins/qtctFeatureEngine.js",
  "/map/layers/portable/representative-pins/representativePinsCore.js",
  "/map/layers/portable/representative-pins/representativePinsPortable.html",
  "/map/layers/portable/representative-pins/representativePinsPortable.svg",
  "/map/layers/portable/representative-pins/runtime.package.json",
  "/map/layers/portable/representative-pins/runtimeCache.js",
  "/map/layers/portable/river-level/layer.package.json",
  "/map/layers/portable/river-level/riverLevelDetail.js",
  "/map/layers/portable/river-level/riverLevelLayer.html",
  "/map/layers/portable/river-level/riverLevelLayer.svg",
  "/map/layers/portable/road-closure/layer.package.json",
  "/map/layers/portable/road-closure/roadClosureDetail.js",
  "/map/layers/portable/road-closure/roadClosureLayer.html",
  "/map/layers/portable/road-closure/roadClosureLayer.svg",
  "/map/layers/portable/svgmap-slawa-client/InterWindowMessaging.js",
  "/map/layers/portable/svgmap-slawa-client/libs/SvgMapElementType.js",
  "/map/layers/portable/svgmap-slawa-client/libs/TransformLib.js",
  "/map/layers/portable/svgmap-slawa-client/libs/UtilFuncs.js",
  "/map/layers/portable/svgmap-slawa-client/runtime.package.json",
  "/map/layers/portable/svgmap-slawa-client/svgMapLayerLib.js",
  "/map/layers/portable/svgmap-slawa-client/svgMapSandboxLayerLib.js",
  "/map/layers/portable/team-activity/appLayersAdmin.html",
  "/map/layers/portable/team-activity/layer.package.json",
  "/map/layers/portable/team-activity/teamActivityAreaLayer.html",
  "/map/layers/portable/team-activity/teamActivityAreaLayer.svg",
  "/map/layers/portable/team-activity/teamActivityCsv.js",
  "/map/layers/portable/team-activity/teamActivityDetail.js",
  "/map/layers/portable/team-activity/teamActivityLayer.html",
  "/map/layers/portable/team-activity/teamActivityLayer.svg",
  "/map/regions/index.json",
  "/map/regions/municipalities-index.json",
  "/map/svgMapAppLayers/basemaps/dynamicDenshiKokudo2016.svg",
  "/map/svgMapAppLayers/basemaps/dynamicOSM_r11.svg",
  "/map/svgMapAppLayers/basemaps/dynamicWMTS.svg",
  "/map/svgMapAppLayers/basemaps/osmTileProviders/osmtp.svg",
  "/map/vendor/svgmapjs/3D_extension/cesiumWindow4_module.js",
  "/map/vendor/svgmapjs/3D_extension/cesiumWindow4.html",
  "/map/vendor/svgmapjs/3D_extension/getProviderViewModels_module.js",
  "/map/vendor/svgmapjs/3D_extension/SVGMapLv0.1_CesiumWrapper_r4module.js",
  "/map/vendor/svgmapjs/CorsProxyModule.js",
  "/map/vendor/svgmapjs/customLayerManagerExtension.js",
  "/map/vendor/svgmapjs/InterWindowMessaging.js",
  "/map/vendor/svgmapjs/libs/BuiltinIcons.js",
  "/map/vendor/svgmapjs/libs/CollidedImagesGetter.js",
  "/map/vendor/svgmapjs/libs/CustomHitTester.js",
  "/map/vendor/svgmapjs/libs/CustomModal.js",
  "/map/vendor/svgmapjs/libs/EssentialUIs.js",
  "/map/vendor/svgmapjs/libs/GeometryCapture.js",
  "/map/vendor/svgmapjs/libs/GlobalMessageDisplay.js",
  "/map/vendor/svgmapjs/libs/GPS.js",
  "/map/vendor/svgmapjs/libs/HashGen.js",
  "/map/vendor/svgmapjs/libs/IframeAdapter4SLaWA.js",
  "/map/vendor/svgmapjs/libs/ImgRenderer.js",
  "/map/vendor/svgmapjs/libs/KMLParser.js",
  "/map/vendor/svgmapjs/libs/LayerManager.js",
  "/map/vendor/svgmapjs/libs/LayerSpecificWebAppHandler.js",
  "/map/vendor/svgmapjs/libs/LayerStyleCustomizer.js",
  "/map/vendor/svgmapjs/libs/LinkedDocOp.js",
  "/map/vendor/svgmapjs/libs/MapTicker.js",
  "/map/vendor/svgmapjs/libs/MapViewerProps.js",
  "/map/vendor/svgmapjs/libs/PathHitTester.js",
  "/map/vendor/svgmapjs/libs/PathRenderer.js",
  "/map/vendor/svgmapjs/libs/PoiHitTester.js",
  "/map/vendor/svgmapjs/libs/ProxyManager.js",
  "/map/vendor/svgmapjs/libs/ResourceLoadingObserver.js",
  "/map/vendor/svgmapjs/libs/ResumeManager.js",
  "/map/vendor/svgmapjs/libs/SandboxWrapper.js",
  "/map/vendor/svgmapjs/libs/ShowPoiProperty.js",
  "/map/vendor/svgmapjs/libs/SvgImageProps.js",
  "/map/vendor/svgmapjs/libs/SvgMapElementType.js",
  "/map/vendor/svgmapjs/libs/SVGMapSerializer_obsoluted.js",
  "/map/vendor/svgmapjs/libs/SVGMapVectorFileRenderer.js",
  "/map/vendor/svgmapjs/libs/SvgStyle.js",
  "/map/vendor/svgmapjs/libs/SvgStyleEditor.js",
  "/map/vendor/svgmapjs/libs/TernarySimultaneousEquationsSolution.js",
  "/map/vendor/svgmapjs/libs/TransformLib.js",
  "/map/vendor/svgmapjs/libs/UAtester.js",
  "/map/vendor/svgmapjs/libs/UtilFuncs.js",
  "/map/vendor/svgmapjs/libs/ZoomPanManager.js",
  "/map/vendor/svgmapjs/SVGMapCustomLayersManager_r3module.html",
  "/map/vendor/svgmapjs/SVGMapCustomLayersManagerApp_r3module.js",
  "/map/vendor/svgmapjs/SVGMapCustomLayersManagerClient.js",
  "/map/vendor/svgmapjs/svgMapLayerLib.js",
  "/map/vendor/svgmapjs/SVGMapLv0.1_Authoring_r8_module.js",
  "/map/vendor/svgmapjs/SVGMapLv0.1_Class_r18module.js",
  "/map/vendor/svgmapjs/SVGMapLv0.1_CustomLayersManager_r3module.js",
  "/map/vendor/svgmapjs/SVGMapLv0.1_GIS_r4_module.js",
  "/map/vendor/svgmapjs/SVGMapLv0.1_LayerUI_r6module.js",
  "/map/vendor/svgmapjs/SVGMapLv0.1_r18module.js",
  "/map/vendor/svgmapjs/svgMapSandboxLayerLib.js",
  "/map/vendor/svgmapjs/tests/unittest/EssentialUIs.test.js",
  "/map/vendor/svgmapjs/tests/unittest/GeoMetryCapture.test.js",
  "/map/vendor/svgmapjs/tests/unittest/GPS.test.js",
  "/map/vendor/svgmapjs/tests/unittest/MapTicker.test.js",
  "/map/vendor/svgmapjs/tests/unittest/PathHitTester.test.js",
  "/map/vendor/svgmapjs/tests/unittest/PathRenderer.test.js",
  "/map/vendor/svgmapjs/tests/unittest/PoiHitTester.test.js",
  "/map/vendor/svgmapjs/tests/unittest/ProxyManager.test.js",
  "/map/vendor/svgmapjs/tests/unittest/ResourceLoadingObserver.test.js",
  "/map/vendor/svgmapjs/tests/unittest/resources/mock.html",
  "/map/vendor/svgmapjs/tests/unittest/resources/mockParamerters.js",
  "/map/vendor/svgmapjs/tests/unittest/ResumeManager.test.js",
  "/map/vendor/svgmapjs/tests/unittest/ShowPoiProperty.test.js",
  "/map/vendor/svgmapjs/tests/unittest/SvgImageProps.test.js",
  "/map/vendor/svgmapjs/tests/unittest/SVGMapLv0.1_Class_r18module.test.js",
  "/map/vendor/svgmapjs/tests/unittest/SVGMapLv0.1_GIS.test.js",
  "/map/vendor/svgmapjs/tests/unittest/SvgStyle.test.js",
  "/map/vendor/svgmapjs/tests/unittest/TernarySimultaneousEquationsSolution.test.js",
  "/map/vendor/svgmapjs/tests/unittest/TransformLib.test.js",
  "/map/vendor/svgmapjs/tests/unittest/UAtester.test.js",
  "/map/vendor/svgmapjs/tests/unittest/UtilFuncs.test.js",
  "/map/vendor/svgmapjs/tests/unittest/ZoomPanManager.test.js",
  "/map/webapp/current-map.html",
  "/map/webapp/native-map.css",
  "/map/webapp/native-map.html",
  "/map/webapp/native-map.js",
  "/map/webapp/region-picker.css",
  "/map/webapp/region-picker.html",
  "/map/webapp/region-picker.js",
  "/map/webapp/shared/artifactBrowser.js",
  "/map/webapp/shared/artifactIndex.js",
  "/map/webapp/shared/dataFreshness.js",
  "/map/webapp/shared/layerAlertPoller.js",
  "/map/webapp/shared/layerCatalog.js",
  "/map/webapp/shared/layerControllerBus.js",
  "/map/webapp/shared/layerHealth.js",
  "/map/webapp/shared/layerMessagePolicy.js",
  "/map/webapp/shared/layerPanel.js",
  "/map/webapp/shared/layerSearch.js",
  "/map/webapp/shared/mapMessages.js",
  "/map/webapp/shared/mapUrlState.js",
  "/map/webapp/shared/messagePolicy.js",
  "/map/webapp/shared/nativeLayerImporter.js",
  "/map/webapp/shared/offlineStorageView.js",
  "/map/webapp/shared/regionSelector.js",
  "/map/webapp/shared/runtimeCache.js",
  "/map/webapp/shared/swCachePolicy.js",
  "/map/webapp/shared/swClient.js",
  "/map/webapp/shared/swMessages.js"
];
// ---------------------------------------------------------------------------

const SHELL_CACHE = shellCacheName(SHELL_VERSION);
const STATE_URL = '/__svg3/region-state.json';

/**
 * 保存状態の台帳。{ order: [...], regions: { <id>: meta } }
 * これは「記録」であって「事実」ではない。表示に使う前に必ず実キャッシュと
 * 突き合わせる（外部要因で消えたキャッシュを保存済みと言わないため）。
 */
const readState = async () => {
  try {
    const cache = await caches.open(META_CACHE_NAME);
    const response = await cache.match(STATE_URL);
    if (!response) return { order: [], regions: {} };
    const data = await response.json();
    return {
      order: Array.isArray(data?.order) ? data.order : [],
      regions: data?.regions && typeof data.regions === 'object' ? data.regions : {},
    };
  } catch {
    return { order: [], regions: {} };
  }
};

const writeState = async (state) => {
  try {
    const cache = await caches.open(META_CACHE_NAME);
    await cache.put(STATE_URL, new Response(JSON.stringify(state), {
      headers: { 'Content-Type': 'application/json' },
    }));
  } catch {
    // 台帳を書けなくても保存済み資産は使える。致命ではない。
  }
};

/** 記録ではなく実体を数える。 */
const inspectRegionCache = async (regionId) => {
  const name = regionCacheName(regionId, REGION_VERSION);
  const names = await caches.keys();
  if (!names.includes(name)) return { cacheExists: false, storedCount: 0, bytes: 0 };
  const cache = await caches.open(name);
  const keys = await cache.keys();
  return { cacheExists: true, storedCount: keys.length, bytes: 0 };
};

const regionStatuses = async () => {
  const state = await readState();
  const ids = new Set([
    ...Object.keys(state.regions),
    ...cachedRegionIds(await caches.keys(), REGION_VERSION),
  ]);
  const statuses = [];
  for (const regionId of ids) {
    const meta = state.regions[regionId] || { regionId };
    const actual = await inspectRegionCache(regionId);
    statuses.push(resolveRegionStatus({ meta: { ...meta, regionId }, ...actual }));
  }
  return { state, statuses };
};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    // 明示した一覧だけを入れる。1つ落ちても起動できなくなるより、
    // 落ちたものを記録して残りを揃える方がよい。
    const failures = [];
    await Promise.all(SHELL_ASSETS.map(async (asset) => {
      try {
        const response = await fetch(asset, { cache: 'reload' });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        await cache.put(asset, response);
      } catch (error) {
        failures.push(asset);
      }
    }));
    if (failures.length > 0) {
      // 欠けた shell で activate すると、旧版で動いていた利用者が壊れた新版へ
      // 移される。install を失敗させて旧 Service Worker を生かしたままにする。
      await caches.delete(SHELL_CACHE);
      throw new Error(`[sw] shell install incomplete: ${failures.length} asset(s) failed`);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    // 旧 shell は必ず消す（新旧の資産が混ざるとアプリが壊れる）。
    // 地域キャッシュは版が一致する限り残す（保存済み地域を失わせない）。
    const doomed = obsoleteCacheNames(names, {
      shellVersion: SHELL_VERSION,
      regionVersion: REGION_VERSION,
    });
    await Promise.all(doomed.map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

const shellResponse = async (request) => {
  const cache = await caches.open(SHELL_CACHE);
  // native-map.html?regionId=... のようにクエリ付きで来るので検索文字列は無視する。
  const cached = await cache.match(request, { ignoreSearch: true });
  if (cached) return cached;
  return fetch(request);
};

const regionResponse = async (request) => {
  const names = await caches.keys();
  for (const name of names) {
    if (parseCacheName(name)?.kind !== 'region') continue;
    const cache = await caches.open(name);
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) return cached;
  }
  // 未保存の地域はネットワークへ。オフラインならここで失敗する。
  // 「保存済みであるかのように見せない」ことが重要。
  return fetch(request);
};

self.addEventListener('fetch', (event) => {
  const request = event.request;
  let url;
  try {
    url = new URL(request.url);
  } catch {
    return;
  }
  const kind = classifyRequest({
    pathname: url.pathname,
    sameOrigin: url.origin === self.location.origin,
    method: request.method,
  });

  // dynamic / external / ignore では respondWith を呼ばない。
  // ここで肩代わりすると鮮度判定が壊れる。
  if (kind === 'shell') {
    event.respondWith(shellResponse(request));
    return;
  }
  if (kind === 'region') {
    event.respondWith(regionResponse(request));
  }
});

const cacheRegion = async (regionId, { pinned = false, onProgress } = {}) => {
  const manifestUrl = `/map/regions/${encodeURIComponent(regionId)}/asset-manifest.json`;
  const response = await fetch(manifestUrl, { cache: 'reload' });
  if (!response.ok) throw new Error(`asset manifest ${response.status}`);
  const manifest = validateRegionAssetManifest(await response.json(), regionId);
  if (!manifest) throw new Error('invalid region asset manifest');

  const state = await readState();
  const pinnedIds = Object.entries(state.regions)
    .filter(([, meta]) => meta?.pinned === true)
    .map(([id]) => id);
  const plan = planRegionCache({
    regionIds: cachedRegionIds(await caches.keys(), REGION_VERSION),
    incoming: regionId,
    pinned: pinned ? [...new Set([...pinnedIds, regionId])] : pinnedIds,
    usageOrder: state.order,
    max: MAX_CACHED_REGIONS,
  });
  if (!plan.accepted) {
    // 上限が pin で埋まっている。黙って消さず、選択を返す。
    return {
      result: SW_RESULTS.capacityChoice,
      regionId,
      reason: plan.reason,
      pinnedRegions: plan.pinnedRegions || [],
      max: MAX_CACHED_REGIONS,
    };
  }

  const cacheName = regionCacheName(regionId, REGION_VERSION);
  const cache = await caches.open(cacheName);
  const total = manifest.assets.length;
  let stored = 0;
  let bytes = 0;
  const failed = [];
  for (const asset of manifest.assets) {
    try {
      const assetResponse = await fetch(asset, { cache: 'reload' });
      if (!assetResponse.ok) throw new Error(`HTTP ${assetResponse.status}`);
      const buffer = await assetResponse.clone().arrayBuffer();
      await cache.put(asset, assetResponse);
      stored += 1;
      bytes += buffer.byteLength;
    } catch {
      failed.push(asset);
    }
    onProgress?.({ regionId, stored, total, failed: failed.length });
  }

  // 県の範囲に交差する QTCT シャードだけを、runtimeCache が読む保管庫へ入れる。
  // ここへ入れても SW は fetch を肩代わりしないので、オンライン時は必ず
  // ネットワークが先に試され、鮮度バナーの判定はそのまま生きる。
  // オフライン時だけ runtimeCache が source:'cache' として拾う。
  const shards = manifest.dataShards || [];
  let shardsStored = 0;
  let shardBytes = 0;
  if (shards.length > 0) {
    const dataCache = await caches.open(RUNTIME_DATA_CACHE_NAME);
    for (const url of shards) {
      try {
        const shardResponse = await fetch(url, { cache: 'reload' });
        if (!shardResponse.ok) throw new Error(`HTTP ${shardResponse.status}`);
        const text = await shardResponse.text();
        const headers = new Headers(shardResponse.headers);
        // 取得時刻。これが無いと「いつ保存したデータか」を利用者へ出せない。
        headers.set(RUNTIME_STORED_AT_HEADER, new Date().toISOString());
        await dataCache.put(url, new Response(text, {
          status: shardResponse.status,
          statusText: shardResponse.statusText,
          headers,
        }));
        shardsStored += 1;
        shardBytes += new TextEncoder().encode(text).byteLength;
      } catch {
        failed.push(url);
      }
      onProgress?.({ regionId, stored: stored + shardsStored, total: total + shards.length, failed: failed.length });
    }
  }

  const complete = failed.length === 0 && stored === total && total > 0;
  // 途中で通信が切れたものを「保存済み」にしない。実体は残すが記録は不完全とする。
  const nextState = {
    order: touchRegionUsage(state.order, regionId).filter((id) => !plan.evict.includes(id)),
    regions: { ...state.regions },
  };
  for (const id of plan.evict) delete nextState.regions[id];
  nextState.regions[regionId] = {
    regionId,
    pinned: pinned === true || state.regions[regionId]?.pinned === true,
    savedAt: new Date().toISOString(),
    bytes,
    assetCount: total,
    shardCount: shardsStored,
    shardBytes,
    complete,
    label: manifest.label || regionId,
  };
  for (const id of plan.evict) await caches.delete(regionCacheName(id, REGION_VERSION));
  await writeState(nextState);

  return {
    result: SW_RESULTS.regionCached,
    regionId,
    stored,
    total,
    failed: failed.length,
    bytes,
    shardCount: shardsStored,
    shardBytes,
    complete,
    pinned: nextState.regions[regionId].pinned,
    evicted: plan.evict,
  };
};

const removeRegion = async (regionId) => {
  const deleted = await caches.delete(regionCacheName(regionId, REGION_VERSION));
  const state = await readState();
  delete state.regions[regionId];
  await writeState({
    order: state.order.filter((id) => id !== regionId),
    regions: state.regions,
  });
  return { regionId, deleted };
};

const listCachedRegions = async () => {
  const { state, statuses } = await regionStatuses();
  // 台帳に載っていても実体が無いものは掃除しておく（表示と実体を一致させる）。
  const orphaned = statuses.filter((status) => status.state === 'absent').map((s) => s.regionId);
  if (orphaned.length > 0) {
    const regions = { ...state.regions };
    for (const id of orphaned) delete regions[id];
    await writeState({ order: state.order.filter((id) => !orphaned.includes(id)), regions });
  }
  return {
    regions: savedRegionIds(statuses),
    statuses: statuses.filter((status) => status.state !== 'absent'),
    order: state.order,
    max: MAX_CACHED_REGIONS,
    shellVersion: SHELL_VERSION,
    regionVersion: REGION_VERSION,
  };
};

// 保存・削除は「状態を読む → 計画する → 書く」の組で、同時に走ると互いに古い状態を
// 見てしまい上限を超える（実測で上限3に対し4地域が残った）。閲覧による自動保存と
// 利用者の明示保存が重なるのは普通に起きるので、状態を触る操作は直列化する。
let mutationQueue = Promise.resolve();
const serializeMutation = (task) => {
  const result = mutationQueue.then(task, task);
  mutationQueue = result.then(() => {}, () => {});
  return result;
};

/** 進捗などを開いている全ページへ配る（返信ポートは1往復しか使えないため）。 */
const broadcast = async (payload) => {
  const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  for (const client of clients) {
    try {
      client.postMessage(payload);
    } catch {
      // 閉じられたクライアントは無視する。
    }
  }
};

self.addEventListener('message', (event) => {
  const message = parseSwMessage(event.data);
  const reply = (payload) => {
    const port = event.ports && event.ports[0];
    if (port) port.postMessage(payload);
    else event.source?.postMessage?.(payload);
  };
  if (!message) {
    reply({ type: SW_RESULTS.error, error: 'unsupported message' });
    return;
  }

  event.waitUntil((async () => {
    try {
      if (message.type === SW_MESSAGES.cacheRegion) {
        const outcome = await serializeMutation(() => cacheRegion(message.regionId, {
          pinned: message.pinned,
          // 進行中の表示に使う。返信用ポートとは別に、全クライアントへ配る。
          onProgress: (progress) => broadcast({ type: SW_RESULTS.regionProgress, ...progress }),
        }));
        const { result, ...payload } = outcome;
        reply({ type: result, ...payload });
        broadcast({ type: result, ...payload });
        return;
      }
      if (message.type === SW_MESSAGES.removeRegion) {
        const payload = {
          type: SW_RESULTS.regionRemoved,
          ...(await serializeMutation(() => removeRegion(message.regionId))),
        };
        reply(payload);
        // 他のタブの一覧も実体に合わせる。
        broadcast(payload);
        return;
      }
      if (message.type === SW_MESSAGES.listCachedRegions) {
        reply({ type: SW_RESULTS.cachedRegions, ...(await serializeMutation(listCachedRegions)) });
      }
    } catch (error) {
      reply({ type: SW_RESULTS.error, error: String(error?.message || error) });
    }
  })());
});
